version: '3'
services:
  mongodb:
        image: centos/mongodb-34-centos7
        container_name: "mongodb"
        environment:
          - MONGODB_USER=user
          - MONGODB_PASSWORD=password
          - MONGODB_ADMIN_PASSWORD=password
          - MONGODB_DATABASE=showcase
        ports:
            - 27017:27017